Suppose the IQ in a certain population is normally distributed with a mean of mu = 100 and standard deviation of sigma = 15 .
A researcher wants to know if a new drug affects IQ levels, so he recruits 20 patients to try it and records their IQ levels.
The following code shows how to perform a one sample z-test in Python to determine if the new drug causes a significant difference in IQ levels:

In [ ]:
from statsmodels.stats.weightstats import ztest as ztest
#Entering IQ of 20 People
data = [88,92,94,94,96,97,97,97,99,99,105,109,109,109,110,112,112,113,114,115]
ztest(data, value=100)

(1.5976240527147705, 0.1101266701438426)

Here we got two value first one is the z score and the second one is p-value and if Pvalue>significance value then our null hypothesis is Rejected else it is Accepted

In [ ]:
#t-test
ages = [10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [ ]:
import numpy as np
ages_mean = np.mean(ages)
print(ages_mean)

30.34375


In [ ]:
sample_size=10
ages_sample = np.random.choice(ages,sample_size)
ages_sample

array([10, 18, 25, 16, 18, 32, 16, 25, 55, 32])

In [ ]:
from scipy.stats import ttest_1samp
ttest_1samp(ages_sample,ages_mean)

TtestResult(statistic=-1.3907538431949469, pvalue=0.1977237695652708, df=9)

In [ ]:
#Consider another example
#Ages of the college students (Population)
#1 class student mean of all the ages

In [ ]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages = stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages = stats.poisson.rvs(loc=18,mu=30,size=60)
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [ ]:
classA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [ ]:
classA_ages.mean()

46.9

In [ ]:
ttest_1samp(classA_ages,school_ages.mean())

TtestResult(statistic=-9.604796510704091, pvalue=1.139027071016194e-13, df=59)

In [ ]:
if p_value<=0.05:
    print("We are rejecting null hypothesis")
else:
    print("We are accepting null hypothesis")

NameError: name 'p_value' is not defined